[package]
name = "zingo-infra-testutils"
version = "0.1.0"
edition = "2021"
license = "MIT License"

[badges]
github = { repository = "zingolabs/infrastructure/testutils" }

[dependencies]
# Local
zingo-infra-services = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
