[package]
name = "zingo_netutils"
version = "0.1.0"
authors = ["zingo@zingolabs.org"]
edition = "2024"

[dependencies]
http-body-util.workspace = true
http-body.workspace = true
http.workspace = true
hyper-rustls.workspace = true
hyper-util.workspace = true
hyper.workspace = true
prost.workspace = true
tokio-rustls.workspace = true
tonic.workspace = true
tower.workspace = true
webpki-roots = "0.25"


thiserror.workspace = true

time = "=0.3.37"
time-core = "=0.1.2"
zcash_client_backend = { version = "0.18", features = [
    "lightwalletd-tonic",
    "orchard",
    "transparent-inputs",
    "tor",
] }

[features]
test-features = []

[dev-dependencies]
rustls-pemfile.workspace = true
