// this file is generated by build.rs
include!(concat!(env!("OUT_DIR"), "/config.rs"));

use std::path::PathBuf;
pub mod binaries;
pub mod utils;

pub fn get_fetcher_out_dir() -> PathBuf {
    PathBuf::from(FETCHER_OUT_DIR)
}
