name: Cargo Checkmate

on:
  workflow_call:
    inputs:
      toolchain:
        description: Rust toolchain to use
        type: string
        default: stable
      rustflags:
        description: RUSTFLAGS passed via env
        type: string
        default: "-D warnings"

jobs:
  cargo-checkmate:
    name: Cargo checkmate
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        phase: [build, check, clippy, doc, format]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run cargo-checkmate
        uses: ./.github/actions/cargo-checkmate
        with:
          toolchain: ${{ inputs.toolchain }}
          rustflags: ${{ inputs.rustflags }}
          phase: ${{ matrix.phase }}
