name: Cargo nextest

on: [workflow_call]

jobs:
  cache-nextest:
    name: Cache nextest
    runs-on: ubuntu-24.04
    if: github.event.pull_request.draft == false
    steps:
      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-nextest

  cargo-nextest:
    name: Cargo nextest
    strategy:
      matrix:
        phase: [build, check, clippy, doc, format]
    needs: cache-nextest
    runs-on: ubuntu-24.04
    if: github.event.pull_request.draft == false
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-nextest

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run cargo nextest
        run: cargo nextest run ${{ matrix.phase }}

