name: Cargo Checkmate

on:
  workflow_call:
    inputs:
      toolchain:
        description: Rust toolchain to use
        type: string
        default: stable
      rustflags:
        description: RUSTFLAGS passed via env
        type: string
        default: "-D warnings"
      doc-all-features:
        description: Run cargo doc with --all-features instead of cargo-checkmate doc
        type: string
        default: 'false'

jobs:
  cargo-checkmate:
    name: Cargo checkmate
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        phase: [build, check, clippy, doc, format]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ inputs.toolchain }}

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Run cargo-checkmate
        uses: ./.github/actions/cargo-checkmate
        with:
          toolchain: ${{ inputs.toolchain }}
          rustflags: ${{ inputs.rustflags }}
          phase: ${{ matrix.phase }}
          doc-all-features: ${{ inputs.doc-all-features }}
