name: CI - Nightly

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  pr-checks:
    uses: ./.github/workflows/ci-pr.yaml

  cargo-hack-build:
    uses: ./.github/workflows/cargo-hack.yaml
    with:
      hack-subcommand: build
