name: CI - PR

on:
  workflow_call:
  workflow_dispatch:
  push:
    tags:
      - '**'
  pull_request:

jobs:
  reject-trailing-whitespace:
    uses: ./.github/workflows/trailing-whitespace.yaml

  cargo-shear:
    name: Cargo Shear
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run cargo-shear
        uses: ./.github/actions/cargo-shear.yml

  cargo-checkmate:
    uses: ./.github/workflows/cargo-checkmate.yaml

  cargo-hack-check:
    name: Cargo Hack Check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run cargo-hack
        uses: ./.github/actions/cargo-hack.yml
        with:
          hack-subcommand: check
