//! Test fixtures for running client RPC tests from external crates
//!
//! For validator/indexer development, the struct must be added to this crate (validator.rs / indexer.rs)
//! and the test fixtures must be expanded to include the additional process
//!
//! If running test fixtures from an external crate, the chain cache should be generated by running a
//! `generate_chain_cache` function: `generate_zcashd_chain_cache()` or `generate_zebrad_large_chain_cache()`
//! which will cache the chain in a `CARGO_MANIFEST_DIR/chain_cache/client_rpcs` directory
//!
//! ```ignore(incomplete)
//! #[ignore = "not a test. generates chain cache for client_rpc tests."]
//! #[tokio::test]
//! async fn generate_zcashd_chain_cache() {
//!   zcash_local_net::test_fixtures::generate_zcashd_chain_cache(
//!     None,
//!     None,
//!     None,
//!   )
//!   .await;
//! }
//! ```

use zcash_local_net::{
    indexer::lightwalletd::Lightwalletd,
    process::Process,
    utils,
    validator::{zebrad::Zebrad, Validator as _},
    LocalNet,
};
/// Generates zebrad chain cache for client RPC test fixtures requiring a large chain
pub async fn generate_zebrad_large_chain_cache() {
    let mut local_net = LocalNet::<Zebrad, Lightwalletd>::launch_default()
        .await
        .unwrap();

    local_net.validator().generate_blocks(150).await.unwrap();

    let chain_cache_dir = utils::chain_cache_dir();
    if !chain_cache_dir.exists() {
        std::fs::create_dir_all(chain_cache_dir.clone()).unwrap();
    }
    local_net
        .validator_mut()
        .cache_chain(chain_cache_dir.join("client_rpc_tests_large"))
        .await
        .expect("cache_chain failed");
}

// FIXME: could've not been ignored, but relies on zingolib.
/// Generates zcashd chain cache for client RPC test fixtures
#[ignore = "FIXME: could've not been ignored, but relies on zingolib"]
pub async fn generate_zcashd_chain_cache() {
    let chain_cache_dir = utils::chain_cache_dir();
    if !chain_cache_dir.exists() {
        std::fs::create_dir_all(chain_cache_dir.clone()).unwrap();
    }
}
