//! Test fixtures for running client RPC tests from external crates
//!
//! For validator/indexer development, the struct must be added to this crate (validator.rs / indexer.rs)
//! and the test fixtures must be expanded to include the additional process
//!
//! If running test fixtures from an external crate, the chain cache should be generated by running the
//! `generate_zebrad_large_chain_cache()` function, which will cache the chain in a
//! `CARGO_MANIFEST_DIR/chain_cache/client_rpc_tests_large` directory

use zcash_local_net::{
    process::Process,
    utils,
    validator::{Validator as _, zebrad::Zebrad},
};

/// Generates zebrad chain cache for client RPC test fixtures requiring a large chain
pub async fn generate_zebrad_large_chain_cache() {
    let mut zebrad = Zebrad::launch_default().await.unwrap();

    zebrad.generate_blocks(150).await.unwrap();

    let chain_cache_dir = utils::chain_cache_dir();
    if !chain_cache_dir.exists() {
        std::fs::create_dir_all(chain_cache_dir.clone()).unwrap();
    }
    zebrad
        .cache_chain(chain_cache_dir.join("client_rpc_tests_large"))
        .await;
}
